### PR TITLE
[#8] fix grape loading

### PR DESCRIPTION
**Pull request by kapone89**
[Review on Reviewable](https://reviewable.io/reviews/monterail/grape-kaminari/25)

### CODE REVIEW

**Comment by Ostrzy** [comment]
Code is obviously fine, but I will request fix for commit message. Firstly the first word should be capitalized. Secondly, I think some explanation in commit description why this was added would be nice. And last thing - tests fail, but I see it is also the case for master, so not the place to fix it :)

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- lib/grape/kaminari.rb @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Comment by kapone89** [comment]
I now ok?

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Comment by kapone89** [comment]
*is now ok?

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Comment by Ostrzy** [comment]
I was thinking about something like
```
[#8] Fix gem loading order

When grape-kaminari was defined before grape there was `uninitialized
constant Grape::Validations` error.
```

I know that it's nitpicking but I believe that verbose commit messages are really helpful. I also know how hard it's to keep drill of making them properly. I hope I will be forgiven.

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Comment by hodak** [comment]
I might not understand something from this commit message.
Commit adds `require 'grape'` that wasn't there before, not move it higher. But commit message says "when grape-kaminari was defined before grape...". Am I missing something? 

---

Review status: all files reviewed, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Comment by kapone89** [comment]
I hope now it's clear ;-)

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/grape-kaminari/25)

**Pull request merged**
